version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations/000_create_migrations_table.sql:/docker-entrypoint-initdb.d/000_create_migrations_table.sql
      - ./migrations/001_create_todos_table.sql:/docker-entrypoint-initdb.d/001_create_todos_table.sql
      - ./migrations/002_add_description_field.sql:/docker-entrypoint-initdb.d/002_add_description_field.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo-network

  # Todo API Service
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: todo-api
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - todo-network

  # Database initialization service
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
      target: build
    container_name: todo-db-init
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: postgres
      DB_PASSWORD: password
    depends_on:
      postgres:
        condition: service_healthy
    command: ["node", "scripts/setup-db.js"]
    networks:
      - todo-network
    restart: "no"

volumes:
  postgres_data:

networks:
  todo-network:
    driver: bridge
