version: '3.8'

services:
  # PostgreSQL Database for Development
  postgres:
    image: postgres:15-alpine
    container_name: todo-postgres-dev
    environment:
      POSTGRES_DB: todo_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./migrations/000_create_migrations_table.sql:/docker-entrypoint-initdb.d/000_create_migrations_table.sql
      - ./migrations/001_create_todos_table.sql:/docker-entrypoint-initdb.d/001_create_todos_table.sql
      - ./migrations/002_add_description_field.sql:/docker-entrypoint-initdb.d/002_add_description_field.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todo_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - todo-dev-network

  # Todo API Service for Development
  todo-api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: todo-api-dev
    environment:
      NODE_ENV: development
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: todo_db
      DB_USER: postgres
      DB_PASSWORD: password
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - todo-dev-network

volumes:
  postgres_dev_data:

networks:
  todo-dev-network:
    driver: bridge
